vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       tricks:
           uri_prefix: '%upload_dir%'
           upload_destination: '%kernel.project_dir%/public%upload_dir%/tricks'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true