@startuml
skinparam backgroundcolor AntiqueWhite/#EBAF10
scale 650 width

skinparam class {
    BackgroundColor #F2621F
    ArrowColor #631FF2
    BorderColor #DB2790
}

header ""

TITLE " Sequence delete a trick"

actor User

box "Application" #F7F2E0

participant System #FFBBBB
database Database #DarkSalmon

User -> System :click on a edit a trick
activate System #Salmon
System -> Database: Request Content
activate Database #DarkSalmon
Database --> System: Response: 200
deactivate Database
System --> User: display edit trick page
User -> System: click on delete
System -> User: ask for confirmation
User -> System: confirm
System -> Database: Request delete
activate Database #DarkSalmon
Database --> System: Response: 200
deactivate Database
System --> User: Success message
deactivate System

@enduml
