@startuml forgotten password
skinparam backgroundcolor AntiqueWhite/#EBAF10
scale 650 width

skinparam class {
    BackgroundColor #F2621F
    ArrowColor #631FF2
    BorderColor #DB2790
}

header ""

TITLE "Sequence forgotten password"
skinparam backgroundcolor AntiqueWhite/#EBAF10
scale 650 width

skinparam class {
    BackgroundColor #F2621F
    ArrowColor #631FF2
    BorderColor #DB2790
}

header ""

TITLE "Sequence forgotten password"

actor ConnectedUser

box "Application" #F7F2E0

participant System #FFBBBB
database Database #DarkSalmon
participant Mailer #Salmon

ConnectedUser -> System: Browse forgotten password
System --> ConnectedUser: Display reset form

alt #green valid form
ConnectedUser -> System: submit
activate System #Salmon
System -> Database: Request to find user
activate Database #DarkSalmon
Database --> System: Response: 200
deactivate Database
activate System
System -> System: create a token
System -> Database: Persist token for user
deactivate System
activate Database #DarkSalmon
Database -> System : Reponse :200
deactivate Database
System -> ConnectedUser: display notification
System -> Mailer: ask for email
activate Mailer #SaddleBrown
Mailer -> System: Email ready
deactivate Mailer
System -> ConnectedUser: Email send
ConnectedUser -> System: click on link
activate System
System -> Database: check token
activate Database #DarkSalmon
Database -> System: token ok
deactivate Database
System -> ConnectedUser: display form to change password
deactivate System
ConnectedUser --> System: submit new password
System ->Database: save new password
Database --> System: Reponse 200
System --> ConnectedUser: display form to connect
ConnectedUser -> System: fill form
System -> ConnectedUser: display backoffice & notify password is changed
deactivate System

else #red invalid form
ConnectedUser -> System: submit
activate System #Salmon
System --> ConnectedUser : Display fields in errors
deactivate System
else #yellow wrong email
ConnectedUser -> System: submit
activate System #Salmon
System --> ConnectedUser : Display email not registered
deactivate System
else #gray invalid Token
ConnectedUser -> System: submit
activate System #Salmon
System --> ConnectedUser : Display token is expirate
deactivate System

end
@enduml

actor ConnectedUser

box "Application" #F7F2E0

participant System #FFBBBB
database Database #DarkSalmon
participant Mailer #Salmon

ConnectedUser -> System: Browse forgotten password
System --> ConnectedUser: Display reset form

alt #green valid form
ConnectedUser -> System: submit
activate System #Salmon
System -> Database: Request to find user
activate Database #DarkSalmon
Database --> System: Response: 200
deactivate Database
System -> Database: Request a token for user
activate Database #DarkSalmon
Database -> System : Reponse :200
deactivate Database
System -> Mailer: Request send Email
activate Mailer #SaddleBrown
Mailer --> System: prepare email (reponse 200)
System --> ConnectedUser: Send Email
ConnectedUser -> System: click on email link
System --> ConnectedUser: display form
ConnectedUser --> System: submit new password
System ->Database: save new password
Database --> System: Reponse 200
System --> ConnectedUser: display form to connect
deactivate Mailer
deactivate System

else #red invalid form
ConnectedUser -> System: submit
activate System #Salmon
System --> ConnectedUser : Display fields in errors
deactivate System

else #red wrong email

ConnectedUser -> System: submit
activate System #Salmon
System --> ConnectedUser : Display email not registered
deactivate System

end
@enduml